# Generated by Django 4.2.7 on 2023-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_one', models.IntegerField()),
            ],
        ),
    ]
