# Generated by Django 5.0 on 2023-12-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('input', models.CharField(max_length=755)),
                ('output', models.IntegerField()),
                ('percentage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'material_transaction',
            },
        ),
        migrations.DeleteModel(
            name='MaterialTransaction',
        ),
    ]
